### ISSUE TITLE
Failed to get screenshot for some of the specs

### ISSUE THREAD

**Issue by vsathyak** [mlison/protractor-jasmine2-screenshot-reporter#25]
It was working fine in my windows machine and screwed up with this error after switching to Mac. 

.Failed to get screenshot: UnknownError: unknown error: cannot take screenshot
from unknown error: Failed to capture tab: unknown error
JavaScript stack:
Error: Failed to capture tab: unknown error
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at Object.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:37:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:72:7)
  (Session info: chrome=45.0.2454.93)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.10.5 x86_64)

**Comment by vsathyak** [comment]
This is not a valid issue.. So I am closing it.
