### ISSUE TITLE
require('string.prototype.startsWith')

### ISSUE THREAD

**Issue by diwu1989** [mlison/protractor-jasmine2-screenshot-reporter#3]
You capitalized the startsWith, should be `startswith` lowercase!

``` js
> require('string.prototype.startsWith');
Error: Cannot find module 'string.prototype.startsWith'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:1
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
```

**Comment by mlison** [comment]
Thanks for spotting that, fixed.
bea6cf4583c8b9bc32a9b71694998961acde0dbb
