### ISSUE TITLE
Report file not found

### ISSUE THREAD

**Issue by msutula** [mlison/protractor-jasmine2-screenshot-reporter#52]
This error happens when running a test suite that only has a single test. As soon as another it block is added (can be even empty), this issue no longer exists.

`Error: ENOENT: no such file or directory, open 'C:\...\e2e\reports\10-Mar-2016-13h-10m\report.html'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at Object.fs.appendFileSync (fs.js:1283:6)
    at Jasmine2ScreenShotReporter.jasmineDone (C:\...\node_modules\protractor-jasmine2-screenshot-reporter\index.js:482:10)
    at dispatch (C:\Users\...\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1966:28)
    at ReportDispatcher.jasmineDone (C:\Users\...\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1949:11)
    at C:\Users\...\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:758:18
    at QueueRunner.clearStack (C:\Users\...\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:660:9)
    at QueueRunner.run (C:\Users\...\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1881:12)
[launcher] Process exited with error code 1
`

**Comment by mlison** [comment]
Yep this is semi-related to #10, protractor doesn't wait until all processes exit - temporary fix [here](https://github.com/mlison/protractor-jasmine2-screenshot-reporter/issues/10#issuecomment-143647225).
